# Generated by Django 5.2.7 on 2025-12-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('ordre_escalade', models.IntegerField(help_text="Ordre d'escalade (1, 2 ou 3)")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'ordering': ['ordre_escalade'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text="Température qui a déclenché l'incident")),
                ('type_incident', models.CharField(choices=[('trop_bas', 'Température trop basse (< 2°C)'), ('trop_haut', 'Température trop haute (> 8°C)')], max_length=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('tentatives_operateur1', models.IntegerField(default=0)),
                ('tentatives_operateur2', models.IntegerField(default=0)),
                ('tentatives_operateur3', models.IntegerField(default=0)),
                ('commentaires', models.TextField(blank=True)),
                ('accuse_reception', models.BooleanField(default=False)),
                ('date_accuse_reception', models.DateTimeField(blank=True, null=True)),
                ('dht11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='DHT.dht11')),
                ('operateur_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_actuels', to='DHT.operateur')),
                ('operateur_initial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_initiaux', to='DHT.operateur')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_creation'],
            },
        ),
    ]
