# Generated by Django 5.2.7 on 2025-12-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_operateur_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Utilisateur Django associé pour l'authentification", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateur_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
